#! /usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../", __FILE__)

require 'grpc'
require 'hello_services_pb'

class GreeterServer < Hello::Greeter::Service
  def say_hello(empty, _unused_call)
    puts 'hello'
    Hello::Reply.new(message: "Hello gRPC")
  end

  def say_name(hello_req, _unused_call)
    puts "name: #{hello_req.name}"
    Hello::Reply.new(message: "Hello #{hello_req.name}")
  end
end

s = GRPC::RpcServer.new
port = '50051'
s.add_http2_port('0.0.0.0:50051', :this_port_is_insecure)
s.handle(GreeterServer)

puts "Start port #{port}"
s.run_till_terminated_or_interrupted([1, 'int', 'SIGQUIT'])
