#! /usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../", __FILE__)

require 'grpc'
require 'hello_services_pb'

# https://grpc.io/docs/guides/auth.html#ruby
stub = Hello::Greeter::Stub.new('localhost:50051', GRPC::Core::Credentials.new(load_certs))

puts "call say_hell"
stub.say_hello(Google::Protobuf::Empty.new).to_json

puts "call say_name with 'World'"
puts stub.say_name(Hello::Request.new(name: 'World')).to_json
